### ISSUE TITLE
parser function is looking for $MINPORT and $MAXPORT variables that don't exist

### ISSUE THREAD

**Issue by fsrob** [TDSSEC/AIO-Enum#5]
Probably needs a re-write of the function

**Comment by TDSSEC** [comment]
Function now uses a sequence of 1-65535 for all ports, instead of looking for the variables MINPORT and MAXPORT.

This ensures all ports, both TCP and UDP are identified on all scans. Will prevent issues arising from custom input if someone entered ports 1-1024,80,443 etc.

parsers.sh updated.

`for n in $(seq 1 65535);`
